#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
shader_dir="$root/lib/zaniah/gpu/vulkan"
glslangValidator -V "$shader_dir/scene.vert" -o "$shader_dir/scene.vert.spv"
glslangValidator -V "$shader_dir/scene.frag" -o "$shader_dir/scene.frag.spv"
